### ISSUE TITLE
Loading columns with leading 0's drops data, misinterprets data type

### ISSUE THREAD

**Issue by dpsspatial** [wireservice/csvkit#977] opened 2018-08-07 21:45 UTC
Perhaps a niche issue, but since we deal with data from the Census, as well as the City and County - both of which store ID's with leading zero's, this is an important one when using this invaluable tool.

Columns with leading zeros are misinterpreted as INTEGER and as a result lose the leading zero and the data type is set to numeric instead of character (which preserves the leading 0).

Example dataset:
https://www.denvergov.org/opendata/dataset/city-and-county-of-denver-real-property-residential-characteristics

**Comment by dpsspatial** [comment] 2018-12-07 21:36
I want to re-open this issue to get feedback on the use case from the developers... Thank you!!!

**Comment by jpmckinney** [comment] 2019-02-07 13:39
You can use `--no-inference` to prevent this.

**Comment by dpsspatial** [comment] 2019-02-08 15:48
Doesn't that stop inferring the data types of all columns? 

Unfortunately I might start using FDW for CSV's for big files...

**Comment by jpmckinney** [comment] 2019-02-10 12:51
There's an open issue to allow column-specific inference: #151. Closing as duplicate.

**Comment by mingfang** [comment] 2022-06-27 16:33
please re-open
I don't think this is a duplicate of #151
Dropping the leading `0` and interpreting the column as numeric is just plain wrong.
In fact, people intentionally put a leading zero in there as a hint that the column is not numeric but it's a varchar instead.

**Comment by jpmckinney** [comment] 2022-06-28 14:40
Yes, and this is why #151 is open.

**Comment by shwivel** [comment] 2024-07-28 18:32
It is very frustrating that csvsql drops leading zeros in such string columns which contain only numeric characters (but which contain leading zeros) and loads the result as integers. Many identifier columns contain leading zeros, are stored as text/varchar/etc. in their respective databases, but when csvsql uses a csv export (with the leading zeros there) it chops them off and creates the column as an integer. Why change what is there? Why in the world would the source database -- from which the CSV was exported -- store that column as an integer? (it'd be impossible, because a value with a leading zero cannot be stored as an integer)

Disabling ALL data type detection is obviously not a solution, because then we cannot use csvsql for anything, and/or are forced to define the data type for every column (might as well just not use csvkit, what's the benefit?)

Why is there not an option to disable this very specific odd behavior?

**Closed** 2024-07-30 01:05 UTC
Labels: feature, csvsql
