### ISSUE TITLE
csvstack: handle reordered columns automatically

### ISSUE THREAD

**Issue by domoritz** [wireservice/csvkit#688] opened 2016-12-07 04:08 UTC
Let's say I have two files

```
A,B
1,x
2,y
```

and

```
B,A
z,3
w,4
```

And want to merge them. Right now csvstack will just stack them and not take the column names into account and reorder the columns in the second file.

**Comment by jpmckinney** [comment] 2016-12-07 09:20
What are the actual and expected outputs?

**Comment by onyxfish** [comment] 2016-12-29 14:34
Current output:

```
A,B
1,x
2,y
z,3
w,4
```

I'm going to presume what the OP expected is:

```
A,B
1,x
2,y
3,z
4,w
```

That's not totally unreasonable, but it's def an edge case and this can already be accomplished by piping through csvcut first. I'd take a patch for this, but consider it low priority.

**Comment by onyxfish** [comment] 2016-12-29 16:02
Just realized this is actually a dupe of #245.

**Closed by onyxfish** 2016-12-29 16:02 UTC
Labels: feature, Low Priority
