### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by Mirocow** [wireservice/csvkit#803] opened 2017-02-26 14:30 UTC
```
$ python --version
Python 2.7.13
Successfully installed csvkit-0.9.1 openpyxl-2.2.0b
```

```
in2csv --format=xls --sheet "Импорт тест" /usr/local/var/www/corplan.ru/imports/Импорт\ тест\ 111.xlsx
/usr/local/lib/python2.7/site-packages/xlrd/book.py:439: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
/usr/local/lib/python2.7/site-packages/xlrd/book.py:439: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
No sheet named <'\xd0\x98\xd0\xbc\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 \xd1\x82\xd0\xb5\xd1\x81\xd1\x82'>
```

**Comment by jpmckinney** [comment] 2017-02-26 20:04
What version of Python are you using?

**Comment by jpmckinney** [comment] 2017-02-26 20:04
Also, please run the command again with `-v` and paste the full output here.

**Comment by Mirocow** [comment] 2017-02-27 07:50
```
$ python --version
Python 2.7.13

mirocow ~ $ csvjoin --version
csvjoin 1.0.2
mirocow ~ $ csvcut --version
csvcut 1.0.2
mirocow ~ $ in2csv --version
in2csv 1.0.2
```

but new version (from master) 

```
mirocow ~ $ pip install git+https://github.com/wireservice/csvkit.git
...
Successfully installed csvkit-1.0.2

mirocow ~ $ in2csv --format=xls --sheet '__Импорт тест' /usr/local/var/www/corplan.ru/imports/Импорт\ тест\ 111.xlsx
from_xls() got an unexpected keyword argument 'column_types'
```

**Comment by jpmckinney** [comment] 2017-02-27 14:36
To use master, you also need to install https://github.com/wireservice/agate-excel from master after installing csvkit.

**Comment by jpmckinney** [comment] 2017-02-27 14:37
I can't reproduce. Can you upload the file? (You may need to ZIP it to upload to GitHub.)

**Comment by jpmckinney** [comment] 2017-03-28 17:25
Closing as no file provided after a month.

**Closed by jpmckinney** 2017-03-28 17:25 UTC
Labels: question
