### ISSUE TITLE
agate-sql: csvsql: generating mysql sql fails: VARCHAR requires a length on dialect mysql

### ISSUE THREAD

**Issue by snorkelbuckle** [wireservice/csvkit#758] opened 2017-01-19 17:28 UTC
Running on windows, python 3.6.0

Trying to generate mysql create script and getting error about VARCHAR.  I did see the comment in issue #740 about doing an upgrade from:

`pip install --upgrade -e git+git://github.com/wireservice/csvkit.git@master#egg=csvkit`

..but this did not help.

Error message:

`csvsql --no-inference -i mysql Account.csv`
`(in table 'Account', column 'MasterRecordId'): VARCHAR requires a length on dialect mysql`

Anything I can do to get around this?

**Comment by jpmckinney** [comment] 2017-01-19 18:22
I can't reproduce. Can you share Account.csv?

**Comment by snorkelbuckle** [comment] 2017-01-19 18:25
Hi James,

I’m sorry, I can’t share it as it contains proprietary data.  However, if you can give me some method to debug this, I will do my best.  I have a little experience with python from about 15 years ago, so if you give me some beginner guidance, I should be able to muck around it.

**Comment by snorkelbuckle** [comment] 2017-01-19 18:32
Just realized, I can reproduce with a one row input file.  Here is a piece I can share and it gives same error.

[Account-Test.zip](https://github.com/wireservice/csvkit/files/717442/Account-Test.zip)

**Comment by snorkelbuckle** [comment] 2017-01-19 18:34
I think I just figured it out, csvsql is barfing on the columns that have empty values in quotes.  For example:

`""`

**Comment by jpmckinney** [comment] 2017-01-19 19:35
Seems to be a SQLAlchemy bug:

```
Traceback (most recent call last):
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2329, in visit_create_table
    and not first_pk)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2360, in visit_create_column
    first_pk=first_pk
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 966, in get_column_specification
    column.type, type_expression=column)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 290, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1318, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/james/.virtualenvs/csvkit/bin/csvsql", line 9, in <module>
    load_entry_point('csvkit==1.0.2', 'console_scripts', 'csvsql')()
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/csvkit/utilities/csvsql.py", line 171, in launch_new_instance
    utility.run()
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/csvkit/cli.py", line 113, in run
    self.main()
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/csvkit/utilities/csvsql.py", line 83, in main
    self._failsafe_main()
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/csvkit/utilities/csvsql.py", line 142, in _failsafe_main
    constraints=not self.args.no_constraints
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/agatesql/table.py", line 235, in to_sql_create_statement
    return six.text_type(CreateTable(sql_table).compile(dialect=sql_dialect)).strip() + ';'
  File "<string>", line 1, in <lambda>
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 436, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 26, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 216, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2340, in visit_create_table
    (table.description, column.name, ce.args[0])
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2329, in visit_create_table
    and not first_pk)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2360, in visit_create_column
    first_pk=first_pk
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 966, in get_column_specification
    column.type, type_expression=column)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 290, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/james/.virtualenvs/csvkit/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1318, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: (in table '758', column 'MasterRecordId'): VARCHAR requires a length on dialect mysql
```

**Comment by snorkelbuckle** [comment] 2017-01-19 20:32
Well, I thought I'd just replace all instances of double double quotes and just get rid of them, so that woudl leave nothing between the delimiting commas, that still fails.  When I remove the --no-inference option, then it succeeds!  So csvsql is not passing right information to sqlalchemy then because this is a pretty standard way to indicate a field with "no value".

My problem is that I need to use --no-inference option because otherwise it is just way too slow.  I'm working with a 500,000 row database.  Further, it seems to die with a CSV file that is larger than 2GB, that is a different problem that I'm willing to work with by splitting the CSV so that csvkit can handle it.

**Comment by jpmckinney** [comment] 2017-01-19 20:42
With `--no-inference`, all columns are simply interpreted as text - which is to be expected. However, if SQLAlchemy gets a text column with zero length, it breaks.

Without `--no-inference`, the columns that are all empty strings are interpreted by csvkit as booleans, which SQLAlchemy can handle.

So, definitely an issue with SQLAlchemy. It shouldn't fail on text columns whose values are all zero length.

**Comment by snorkelbuckle** [comment] 2017-01-19 20:55
It still fails if I replace all those double double quotes to have a blank space in the middle, the length is at least one.

**Comment by jpmckinney** [comment] 2017-01-19 21:50
Can you share that new file?

**Comment by snorkelbuckle** [comment] 2017-01-19 22:37
This file gives the same error, all of the empty double quoted fields are replaced with double quote enclosed blank space.
[Account-Test-2.zip](https://github.com/wireservice/csvkit/files/717947/Account-Test-2.zip)

**Comment by jpmckinney** [comment] 2017-01-19 23:03
You need to pass `--blanks` to avoid `" "` being coerced to null.

**Comment by snorkelbuckle** [comment] 2017-01-19 23:14
Okay, thanks, that helps.  Then I can just use a query to empty all the blanks once I get into the sql server.

**Comment by alvesjc** [comment] 2017-03-03 00:23
Hi.

I'm facing the same issue, any news regarding this?
`  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 985, in get_column_specification
    column.type, type_expression=column)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py", line 290, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1342, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: (in table 'table_name', column 'column_name'): VARCHAR requires a length on dialect mysql`

**Comment by alvesjc** [comment] 2017-03-03 00:30
Ok, disregard my last comment.

pip install --upgrade -e git+git://github.com/wireservice/csvkit.git@master#egg=csvkit

solved the issue to me!

Thanks.

**Comment by mikadev** [comment] 2017-08-08 18:24
please can someone fix this thanks

**Comment by jpmckinney** [comment] 2017-08-10 03:50
Fixed by https://github.com/wireservice/agate-sql/pull/28 Until new versions of agate-sql and csvkit are released, you'll have to install the GitHub version of agate-sql on top of your installation of csvkit.

**Closed** 2018-01-28 05:50 UTC
Labels: fixed: upstream
