### ISSUE TITLE
csvlook 1.0.3: Shorting decimals and displaying ellipsis in values

### ISSUE THREAD

**Issue by xmarti6** [wireservice/csvkit#991] opened 2018-10-13 06:35 UTC
Hi, this issue is related to these:
https://github.com/wireservice/csvkit/pull/824
https://csvkit.readthedocs.io/en/1.0.3/tricks.html#python-standard-output-encoding-errors

When piping like:
<../file.tsv |tail -n+2|head|PYTHONIOENCODING=utf8  csvlook -d$'\t' |less -S  

I get values in fields truncated with "ellipsis", e.g: "0.015...". Instead of having three dots i get printed the unicode character corresponding to "ellipsis" u'\u2026', this is why I need to add "PYTHONIOENCODING=utf8" in order to avoid the error "ascii' codec can't encode ...". 

My question here is not in regards to "ellipsis" char, but to know why are "ellipsis" added to the values, instead of being able to see the complete float number without rounding up and without adding ellipsis:  "0.0148232611174"

I want to point out that this is not an issue in version "0.9.2", values are displayed correctly, unfortunately, using that version I come up with the issue: https://github.com/wireservice/csvkit/issues/383   :(

Many thanks in advance

**Comment by jpmckinney** [comment] 2018-11-07 14:37
csvlook makes a best attempt to make data viewable within a regularly-sized shell window, so it truncates some values. (You can always open the CSV in OpenOffice, LibreOffice, Excel, etc. to see full values.)

Closing as duplicate of #941 which is about configuring the number of decimals to display.

**Closed by jpmckinney** 2018-11-07 14:37 UTC
