### ISSUE TITLE
csvstat gives me "'NoneType' object has no attribute 'decimal_formats'" error for tutorial data

### ISSUE THREAD

**Issue by suewonjp** [wireservice/csvkit#821] opened 2017-04-09 03:43 UTC
Whenever I try **csvstat** for the tutorial data, I get the following error and it just stops wherever it detects the error

```
$ csvstat data.csv

  1. "state"

        Type of data:          Text
        Contains null values:  False
        Unique values:         1
        Most common values:    NE (1036x)

  2. "county"

        Type of data:          Text
        Contains null values:  False
        Unique values:         35
        Most common values:    DOUGLAS (760x)
                               DAKOTA (42x)
                               CASS (37x)
                               HALL (23x)
                               LANCASTER (18x)

  3. "fips"

        Type of data:          Number
        Contains null values:  False
        Unique values:         35
'NoneType' object has no attribute 'decimal_formats'
        Most common values:   
```

My environment:

> OS X 10.11.6
> 
> python version : 2.7.10
> 
> pip version : 9.0.1

I installed csvkit via pip yesterday (Apr 8th)

Any idea?

**Comment by jpmckinney** [comment] 2017-04-11 17:40
I can't reproduce - `decimal_formats` occurs nowhere in the code.

Can you run `pip freeze | grep "csvkit\|agate"`

**Comment by maartenbosteels** [comment] 2017-04-14 08:31
Hi, I have the same issue. I installed csvkit yesterday in a virtualenv.

> pip freeze | grep "csvkit\|agate"
agate==1.6.0
agate-dbf==0.2.0
agate-excel==0.2.1
agate-sql==0.5.1
csvkit==1.0.1

**Comment by maartenbosteels** [comment] 2017-04-14 08:40
Steps to reproduce:

$ echo -e "id,desc\n123,test\n" > simple.csv
$ cat simple.csv
id,desc
123,test
$  csvstat simple.csv
  1. "id"

	Type of data:          Number
	Contains null values:  True (excluded from calculations)
	Unique values:         2
'NoneType' object has no attribute 'decimal_formats'
	Most common values:    $

=> No output about the desc column.

My environment matches that of Suewon:
OS.X 10.11.6
python version : 2.7.10
pip 9.0.1

**Comment by jpmckinney** [comment] 2017-04-15 03:58
Can you run csvstat with the `-v` option? Also, try `pip install agate==1.6.1` and running it again.

**Comment by suewonjp** [comment] 2017-04-15 09:11
I got the following by running 'csvstat -v'

> 1. "state"
> 
>         Type of data:          Text
>         Contains null values:  False
>         Unique values:         1
>         Most common values:    NE (1036x)
> 
>   2. "county"
> 
>         Type of data:          Text
>         Contains null values:  False
>         Unique values:         35
>         Most common values:    DOUGLAS (760x)
>                                DAKOTA (42x)
>                                CASS (37x)
>                                HALL (23x)
>                                LANCASTER (18x)
> 
>   3. "fips"
> 
>         Type of data:          Number
>         Contains null values:  False
>         Unique values:         35
>         Most common values:    Traceback (most recent call last):
>   File "/usr/local/bin/csvstat", line 9, in <module>
>     load_entry_point('csvkit==1.0.1', 'console_scripts', 'csvstat')()
>   File "/Library/Python/2.7/site-packages/csvkit/utilities/csvstat.py", line 331, in launch_new_instance
>     utility.run()
>   File "/Library/Python/2.7/site-packages/csvkit/cli.py", line 113, in run
>     self.main()
>   File "/Library/Python/2.7/site-packages/csvkit/utilities/csvstat.py", line 165, in main
>     self.print_stats(table, column_ids, stats)
>   File "/Library/Python/2.7/site-packages/csvkit/utilities/csvstat.py", line 265, in print_stats
>     v = format_decimal(v)
>   File "/Library/Python/2.7/site-packages/babel/numbers.py", line 252, in format_decimal
>     format = locale.decimal_formats.get(format)
> AttributeError: 'NoneType' object has no attribute 'decimal_formats'

Also,

$pip freeze | grep "csvkit\|agate"

> agate==1.6.0
> agate-dbf==0.2.0
> agate-excel==0.2.1
> agate-sql==0.5.1
> csvkit==1.0.1

And,

$sudo pip install agate==1.6.1

> Collecting agate==1.6.1
>   Could not find a version that satisfies the requirement agate==1.6.1 (from versions: 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6.0)
> No matching distribution found for agate==1.6.1

**Comment by jpmckinney** [comment] 2017-04-15 15:25
Ah, yes, sorry, agate 1.6.1 isn't released yet. The backtrace shows that it's an issue with your version of Babel. What's `pip freeze | grep Babel` say?

**Comment by jpmckinney** [comment] 2017-04-15 15:29
Nevermind, seems we need to copy the solution that agate found to the same issue: https://github.com/wireservice/agate/issues/453

**Comment by maartenbosteels** [comment] 2017-04-15 15:37
Babel==2.4.0

**Comment by jpmckinney** [comment] 2017-04-15 15:43
Ok, should be fixed in the next release of csvkit

**Closed** 2017-04-15 15:43 UTC
Labels: question

**Comment by maartenbosteels** [comment] 2017-04-16 09:17
tx !

**Comment by tcn** [comment] 2017-04-27 06:17
The same apparently goes for the format_decimal() in [print_stats()](https://github.com/wireservice/csvkit/blob/master/csvkit/utilities/csvstat.py#L269):

```
# cat foo.csv
foo
123

# csvstat -v foo.csv
  1. "foo"

        Type of data:          Number
        Contains null values:  True (excluded from calculations)
        Unique values:         2
        Most common values:    Traceback (most recent call last):
  File "/usr/local/bin/csvstat", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/csvstat.py", line 335, in launch_new_instance
    utility.run()
  File "/usr/local/lib/python2.7/site-packages/csvkit/cli.py", line 113, in run
    self.main()
  File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/csvstat.py", line 165, in main
    self.print_stats(table, column_ids, stats)
  File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/csvstat.py", line 268, in print_stats
    v = format_decimal(v)
  File "/usr/local/lib/python2.7/site-packages/babel/numbers.py", line 252, in format_decimal
    format = locale.decimal_formats.get(format)
AttributeError: 'NoneType' object has no attribute 'decimal_formats'
```

**Comment by jpmckinney** [comment] 2017-04-27 13:59
@tcn It's the same and will be fixed in the next release.

**Comment by bekicot** [comment] 2017-07-26 03:14
@tcn @suewonjp 
The work around is `csvstat csvfiles --csv`

It will show stats in CSV format :)

**Comment by havardorbech** [comment] 2017-07-31 13:59
@bekicot 
FYI: The suggested work-around does not return all expected output values: 

Specifically, `csvstat input --csv` does not return mean, max, sum, mean, median, stdev, len.

> $ csvcut -c county,acquisition_cost,ship_date out.csv | csvstat --csv
> column_id,column_name,type,nulls,unique,min,max,sum,mean,median,stdev,len,freq
> 1,county,Text,False,35,,,,,,,,"DOUGLAS, DAKOTA, CASS, HALL, LANCASTER"
> 2,acquisition_cost,Number,False,75,,,,,,,,"6800.0, 10747.0, 6000.0, 499.0, 0.0"
> 3,ship_date,Date,False,84,2006-03-07,2014-01-30,,,,,,"2013-04-25, 2013-04-26, 2008-05-20, 2012-04-16, 2006-11-17" 

> 
> $ csvstat acs2012_5yr_population.csv --csv
> column_id,column_name,type,nulls,unique,min,max,sum,mean,median,stdev,len,freq
> 1,fips,Number,False,93,,,,,,,,"31001, 31003, 31005, 31007, 31009"
> 2,name,Text,False,93,,,,,,,,"Adams County, NE, Antelope County, NE, Arthur County, NE, Banner County, NE, Blaine County, NE"
> 3,total_population,Number,False,93,,,,,,,,"31299, 6655, 490, 778, 584"
> 4,margin_of_error,Number,False,15,,,,,,,,"0, 73, 114, 97, 99"

**Comment by bekicot** [comment] 2017-07-31 14:03
@havardorbech Good catch
I was avoiding the error and doesn't really notice the missing values. I only needed the freq column.
Well it is not a work around then, it is a way to avoid errors.

**Comment by jpmckinney** [comment] 2017-08-04 13:19
Isn't this already fixed in csvkit 1.0.2?

**Comment by bekicot** [comment] 2017-08-04 13:23
@jpmckinney 
I was using csvstat 1.0.2. I can't reproduce now as I don't know the problem, and the csv file I forgot which CSV files I use.

**Comment by havardorbech** [comment] 2017-08-04 13:32
@jpmckinney 
@bekicot 

I have this problem using macOS 10.12.6. Can be reproduced using data.csv from tutorial.

Environment:
```
$ pip freeze | grep "csvkit\|agate"
agate==1.6.0
agate-dbf==0.2.0
agate-excel==0.2.1
agate-sql==0.5.2
csvkit==1.0.2

$ pip -V
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)

$ pip freeze | grep Babel
Babel==2.4.0
```

**Comment by jpmckinney** [comment] 2017-08-04 13:38
Can you upload a sample file?

**Comment by havardorbech** [comment] 2017-08-04 13:41
@jpmckinney 
I just edited my previous comment with  `csvcut -v` using tutorial data.
If you need additional files, please be more specific as to what exactly you are looking for:
- sample input file
- output from using csvcut on sample file etc
- other

**Comment by havardorbech** [comment] 2017-08-04 14:04
I thought maybe it could be a localisation issue (ie environment using `,` as decimal separators instead of `.` as used in file).

However, I tested and it doesnt seem to be the case 
(assuming printf and babel use the same decimal separator).

```
$ printf "%f\n" 3.1415
3.141500

$ printf "%f\n" 3,1415
-bash: printf: 3,1415: invalid number
0.000000

```

**Comment by jpmckinney** [comment] 2017-08-04 14:58
I can't reproduce:

```
in2csv examples/realdata/ne_1033_data.xlsx > data.csv
csvcut -c county,acquisition_cost,ship_date data.csv | csvstat -v
```

Is it possible you installed an unreleased version of 1.0.2? Try installing from GitHub to try with 1.0.3.

**Comment by jpmckinney** [comment] 2017-08-04 15:05
Although I can't reproduce, I opened a PR to see if that solution works for you: https://github.com/wireservice/csvkit/pull/878

**Comment by havardorbech** [comment] 2017-08-04 15:17
OK, will try to install from GitHub, although I think it is unlikely I installed an unreleased version.

By coincidence I had to reinstall macOS today, and therefore also had to install pip, brew and csvkit again. I had the same issue before and after reinstalling, and I am pretty sure the environment is identical.

FWIW, below are the warnings I got...

...when installing csvkit (`sudo pip install csvkit`)
```
Installing collected packages: Babel, isodate, six, Unidecode, python-slugify, pytimeparse, leather, future, parsedatetime, agate, xlrd, jdcal, et-xmlfile, openpyxl, agate-excel, dbfread, agate-dbf, sqlalchemy, agate-sql, csvkit
  Running setup.py install for isodate ... done
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-f4DF45-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

...when installing pip
```
Running pip-9.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0Jb78v/pip-9.0.1/egg-dist-tmp-qQxGyb
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.landscape.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.github'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'

```

**Comment by jpmckinney** [comment] 2017-08-04 15:26
On macOS I would recommend not using the system's Python, and instead use Python installed by Homebrew. The system Python causes many problems.

**Comment by havardorbech** [comment] 2017-08-04 15:50
Actually, I did `brew install python` earlier today, which installed 2.7.13_1  

`pyenv install 3.6.1` fails.  Will try to install v 1.0.3 as suggested earlier.
If it still fails, I guess this is a fringe case related to Python.

```
BUILD FAILED (OS X 10.12.6 using python-build 20160602)

Inspect or clean up the working tree at /var/folders/lj/vv0t9wkn36sgtyh_jms0mdy8f7gc39/T/python-build.20170804173714.40004
Results logged to /var/folders/lj/vv0t9wkn36sgtyh_jms0mdy8f7gc39/T/python-build.20170804173714.40004.log

Last 10 log lines:
  File "/private/var/folders/lj/vv0t9wkn36sgtyh_jms0mdy8f7gc39/T/python-build.20170804173714.40004/Python-3.6.1/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/private/var/folders/lj/vv0t9wkn36sgtyh_jms0mdy8f7gc39/T/python-build.20170804173714.40004/Python-3.6.1/Lib/ensurepip/__init__.py", line 189, in _main
    default_pip=args.default_pip,
  File "/private/var/folders/lj/vv0t9wkn36sgtyh_jms0mdy8f7gc39/T/python-build.20170804173714.40004/Python-3.6.1/Lib/ensurepip/__init__.py", line 102, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/lj/vv0t9wkn36sgtyh_jms0mdy8f7gc39/T/python-build.20170804173714.40004/Python-3.6.1/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
make: *** [install] Error 1

```
