### ISSUE TITLE
csvsql: SQLAlchemy: strips [*] from header

### ISSUE THREAD

**Issue by JZirnstein** [wireservice/csvkit#388] opened 2015-03-12 14:45 UTC
csvlook testSQL.csv 

| Header[1] | Header[2] | Header[3] |
| --- | --- | --- |
| 1 | 2 | 3 |
| 4 | 5 | 6 |

 csvsql --query "select \* from testSQL" testSQL.csv | csvlook

| Header | Header | Header |
| --- | --- | --- |
| 1 | 2 | 3 |
| 4 | 5 | 6 |

**Comment by jpmckinney** [comment] 2016-01-23 19:15
The headers are correct on this line: https://github.com/onyxfish/csvkit/blob/7a6f2971cd0ec8abe4f6114166af5fc7bfa3641b/csvkit/utilities/csvsql.py#L129

But they come out wrong here: https://github.com/onyxfish/csvkit/blob/7a6f2971cd0ec8abe4f6114166af5fc7bfa3641b/csvkit/utilities/csvsql.py#L150

**Comment by onyxfish** [comment] 2016-02-05 18:49
I strongly suspect this is going to be a sqlalchemy thing—and probably dialect specific to boot. Marking low because it's a rabbit hole. (Like everything with sqlalchemy.)

**Comment by jpmckinney** [comment] 2017-01-03 18:17
`csvsql --dialect sqlite 388.csv` includes the brackets, but `csvsql --query 'select * from "388"' 388.csv` loses them.

**Comment by jpmckinney** [comment] 2017-08-04 14:01
Confirmed still an issue with SQLAlchemy==1.1.13

**Comment by jpmckinney** [comment] 2024-02-15 18:08
Fixed in SQLAlchemy 2

```
$ cat 388.csv
Header[1],Header[2],Header[3]
1,2,3
4,5,6
```

```
$ csvsql --query 'select * from "388"' 388.csv
Header[1],Header[2],Header[3]
1.0,2.0,3.0
4.0,5.0,6.0
```

**Closed by jpmckinney** 2024-02-15 18:08 UTC
Labels: bug: upstream, csvsql
