### ISSUE TITLE
csvsql: cannot connect using credential file ".mylogin.cnf"

### ISSUE THREAD

**Issue by lrob** [wireservice/csvkit#791] opened 2017-02-10 08:37 UTC
Hello,
as suggested in the documentation I'm storing the credential of my mysql db in .mylogin.cnf.
After the creation of this file, the mysql client (from the command line) is connecting without asking for credential.

However if a run csvsql with the following url: mysql:///dbschema?charset=utf8, it still complains about authentication issues

(_mysql_exceptions.OperationalError) (1045, "Access denied for user 'user'@'localhost' (using password: NO)")

Is there an option or something that I have to specify in the url in order to tell csvsql to read in the .mylogin.cnf for credential information?

Thanks in advance

**Comment by jpmckinney** [comment] 2017-02-10 22:33
Ah, yes, this is a bug.

**Comment by lrob** [comment] 2017-02-11 13:30
Hi,
is it possible to get the same result with another approach? I really would
like to be able to connect without putting the password in the connection
string

thanks in advance

Il 10 feb 2017 11:34 PM, "James McKinney" <notifications@github.com> ha
scritto:

**Comment by jpmckinney** [comment] 2017-02-12 06:07
No, the solution is to fix the bug.

**Comment by jpmckinney** [comment] 2023-10-17 21:54
> as suggested in the documentation I'm storing the credential of my mysql db in .mylogin.cnf.

Hmm, I don't actually see this in our docs. So this would be a feature request, not a bug.

SQLAlchemy 2 doesn't seem to provide any obvious facility for automatically reading these files.

For PostgreSQL, I know that psycopg2 uses libpq, which reads `.pgpass`. I think it's too much for CSV Kit to support the various database configuration files. This should be resolved by database drivers (like libpq, but for MySQL) instead.

**Closed by jpmckinney** 2023-10-17 21:54 UTC
Labels: feature, csvsql
