### ISSUE TITLE
Ignore column indices that don't exist with csvcut

### ISSUE THREAD

**Issue by dhulke** [wireservice/csvkit#983] opened 2018-08-29 02:03 UTC
Today, if I try to csvcut -c 3 file.csv and one of the lines doesn't actually have 3 columns, the script will error out. I think we should have an option to just ignore the error and move on. Using csvjoin for this doesn't quite work.

**Comment by jpmckinney** [comment] 2018-09-04 20:13
I can't reproduce:

```
echo "a,b,c
4" | csvcut -c 3
```

Output:

```
c
""
```

Please follow the [instructions here](https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug) for reporting an issue.

**Comment by jpmckinney** [comment] 2018-11-21 18:33
No answer, so closing.

**Closed by jpmckinney** 2018-11-21 18:33 UTC
Labels: question
