### ISSUE TITLE
in2csv option  --write-sheets "-" fails

### ISSUE THREAD

**Issue by raveslave** [wireservice/csvkit#887] opened 2017-09-10 11:51 UTC
Getting an exception using the all sheets argument on 1.0.2
_Python 2.7.13_

```
 --write-sheets WRITE_SHEETS
                        The names of the Excel sheets to write to files, or
                        "-" to write all sheets.

using
in2csv filewithmanysheets.xls --write-sheets "-"
```

```
Traceback (most recent call last):
  File "/usr/local/bin/in2csv", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/in2csv.py", line 180, in launch_new_instance
    utility.run()
  File "/usr/local/lib/python2.7/site-packages/csvkit/cli.py", line 114, in run
    self.main()
  File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/in2csv.py", line 163, in main
    tables = agate.Table.from_xls(self.input_file, sheet=sheets, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/agateexcel/table_xls.py", line 30, in from_xls
    book = xlrd.open_workbook(file_contents=path.read())
  File "/usr/local/lib/python2.7/site-packages/xlrd/__init__.py", line 116, in open_workbook
    with open(filename, "rb") as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Testing with --names on the same file works fine and outputs 13 sheet names, no blanks no unicode.

**Comment by jpmckinney** [comment] 2017-09-10 15:34
Is it possible for you to share the Excel file? (or another Excel file that reproduces the error?)

**Comment by raveslave** [comment] 2017-09-10 15:48
I'm afraid the contents prevents me from doing so. I don't have excel myself so opened the file in mac Numbers to just clear the table-contents (except the headers and left one dummy row in each sheet), export to .xlsx (can't choose .xls in numbers), then the --write-sheets "-" works...

Let me know how I can help debug the .xls file that breaks further.

ps. sheets came out as
```
manysheets_0.csv
manysheets_1.csv
```
I was expecting the actual sheet-names to be kept in the output filenames
```
manysheets_[sheetname].csv
manysheets_resistors.csv
manysheets_inductors.csv
```

**Comment by jpmckinney** [comment] 2017-09-26 01:05
Hmm, not sure how to resolve the issue if I can't reproduce it. If re-exporting the file from Numbers resolves the issue, then the problem is likely a slightly malformed Excel produced by a slightly misimplemented Excel library (in which case, csvkit isn't likely to fix the issue). Where does the original file come from?

**Comment by jpmckinney** [comment] 2017-09-26 01:05
Also, for writing sheet names instead of sheet indexes, please open a new issue.

**Comment by jpmckinney** [comment] 2017-10-26 00:58
Closing, as I assume the Excel file was malformed.

**Closed by jpmckinney** 2017-10-26 00:58 UTC
Labels: question

**Comment by gornostaevdev** [comment] 2017-11-07 11:50
Same issue here: --write-sheets="-" leading to coercing to Unicode: need string or buffer, NoneType found

1251 encoding sheets, --names output is fine,
`...
usa
kor
jp
ЕВРОПА`
 but when output file is specified - 
`'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)`

**Comment by jpmckinney** [comment] 2017-11-07 15:27
@gornostaevdev Can you provide the information described here, so that I can reproduce and correct the error? https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug
