### ISSUE TITLE
agate: csvlook: Add an option to allow unnamed columns

### ISSUE THREAD

**Issue by chuanconggao** [wireservice/csvkit#787] opened 2017-01-31 18:02 UTC
Is it possible to add an option to prevent agate automatically naming unnamed columns. 

For example, I want to preview the following CSV, where the first column does not have name:

|               | 1st Half | 2nd Half | Total |
| ------------- | -------- | -------- | ----- |
| Central Wash. |       52 |       45 |    97 |
| Simon Fraser  |       44 |       41 |    85 |

**Comment by jpmckinney** [comment] 2017-01-31 18:20
Does naming the column cause a problem?

**Comment by chuanconggao** [comment] 2017-01-31 18:27
I am using csvlook in a workflow to generate HTML automatically like this:
`csvlook sth.csv | pandoc`

As I cannot control the CSV, there are inevitably empty column names. I want to make sure the rendered HTML also has empty column names instead of automatically generated ones, to keep the appearance consistent.

**Comment by jpmckinney** [comment] 2017-01-31 18:35
I created an issue on agate: https://github.com/wireservice/agate/issues/668

**Comment by jpmckinney** [comment] 2017-08-04 13:53
Changing agate isn't likely, so I'm going to mark this duplicate of #814, which should allow you to explicitly rename columns to the empty string.

**Closed by jpmckinney** 2017-08-04 13:53 UTC
Labels: bug: upstream, Low Priority
