### ISSUE TITLE
in2csv, cp1251.py: 'charmap' codec can't encode character '\xd7'

### ISSUE THREAD

**Issue by 0f27** [wireservice/csvkit#786] opened 2017-01-30 13:02 UTC
Hello guys.
I am facing it especially with Cyrillic-contained files encoded in CP1251.
What i do:

```bash
in2csv -v -f xls --sheet sheet2 some_file.xlsx
```

Here is the output:
```
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\boto\plugin.py:40: Pendintation for alternative uses
Traceback (most recent call last):
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\runpy.py", line 184, in _run_m
    "__main__", mod_spec)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\runpy.py", line 85, in _run_co
    exec(code, run_globals)
  File "C:\Users\user\AppData\Roaming\workdir\Anaconda3\Scripts\in2csv.exe\__main__.py", l
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\utilities
    utility.run()
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\cli.py",
    self.main()
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\utilities
    table.to_csv(self.output_file)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\table\to_c
    writer.writerow(self._column_names)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\csv_py3.py
    self.writer.writerow(row)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\encodings\cp1251.py", line 19,
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xd7' in position 104: character maps to <undefined>
```

**Comment by jpmckinney** [comment] 2017-01-30 14:10
Can you remove `-f xls` and re-run the command? (It's an xlsx file, not a xls file)

**Comment by 0f27** [comment] 2017-01-30 14:51
Sure. Here it is:

```
 in2csv -v --sheet sheet2 some_file.xlsx
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\boto\plugin.py:40: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Traceback (most recent call last):
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Roaming\workdir\Anaconda3\Scripts\in2csv.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\utilities\in2csv.py", line 117, in launch_new_instance
    utility.run()
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\cli.py", line 113, in run
    self.main()
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\utilities\in2csv.py", line 57, in main
    self.input_file = open(self.args.input_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../some_file.xlsx'
```

But it is actually **xls** file, **not xlsx**. With **-f xls** flag it works with another sheets in the same file (which does not contain Cyrillic). So it is really xls just named as xlsx. I mentioned it because maybe format does matter. Sorry if it confused you.

**Comment by jpmckinney** [comment] 2017-01-30 18:38
Could you share the file?

**Comment by 0f27** [comment] 2017-01-31 11:53
Sure. I just removed sensitive data from file...
[Here it is](https://mega.nz/#!NIURBYgC!3o0aSp0uFz8OqQSfO4PZMQ3NqzBDgKvNm_EpKSto2t8)
Still with same error.

**Comment by 0f27** [comment] 2017-01-31 13:32
Same with CP866 codepage if it does matter:
```cmd
C:\Users\user\Downloads>in2csv -v --sheet sheet2 some_file.xlsx
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\boto\plugin.py:40: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\table\__init__.py:90: UnnamedColumnWarning: Column 12 has no name. Using "m".
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\table\__init__.py:90: UnnamedColumnWarning: Column 13 has no name. Using "n".
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\table\__init__.py:90: UnnamedColumnWarning: Column 14 has no name. Using "o".
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\table\__init__.py:90: UnnamedColumnWarning: Column 15 has no name. Using "p".
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\table\__init__.py:90: UnnamedColumnWarning: Column 16 has no name. Using "q".
c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\table\__init__.py:90: UnnamedColumnWarning: Column 17 has no name. Using "r".
Traceback (most recent call last):
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Roaming\workdir\Anaconda3\Scripts\in2csv.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\utilities\in2csv.py", line 117, in launch_new_instance
    utility.run()
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\cli.py", line 113, in run
    self.main()
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\csvkit\utilities\in2csv.py", line 107, in main
    table.to_csv(self.output_file)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\table\to_csv.py", line 38, in to_csv
    writer.writerow(self._column_names)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\site-packages\agate\csv_py3.py", line 91, in writerow
    self.writer.writerow(row)
  File "c:\users\user\appdata\roaming\workdir\anaconda3\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xd7' in position 104: character maps to <undefined>
```

**Comment by jpmckinney** [comment] 2017-01-31 17:02
@0f27 Can you upload the GitHub? (You can use a ZIP if XLSX file extension is not allowed). I can't download from Mega.

**Comment by jpmckinney** [comment] 2017-01-31 18:26
I can't reproduce the error. I think the issue is related to your environment.

**Comment by jpmckinney** [comment] 2017-01-31 18:29
I'm not sure how you're controlling whether cp1251 or cp866 are used, but it should be utf8.

**Comment by jpmckinney** [comment] 2017-02-28 16:09
Closing as haven't received clarification in a month regarding why different code pages are used for presumably the same file.

**Closed by jpmckinney** 2017-02-28 16:09 UTC
Labels: question
